[package]
name = "loragw-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
libm = "0.2.11"
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serialport = "4.7.0"
thiserror = "2.0.11"
tracing = "0.1.41"
